
package taller_lei32_7;

import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {
    int registros = 0;
    Object[][] matriz = new Object[5][4];
    String[] nombres = new String[5];
    int[] intentos = new int[5];
    String[] tipos = new String[5];
    String[] plantasConFlor = new String[5];
    
    
    public Dashboard() {
        
        initComponents();
        panelConFlor.setVisible(false);
        panelSinFlor.setVisible(false);
        
    }
    
    public void imprimirIntentos(){
        String msj = "Cantidad de intentos \n";
        for (int i = 0; i < 5; i++) {
            msj += nombres[i]+" con "+intentos[i]+ " Intentos\n"; 
        }
        
        JOptionPane.showMessageDialog(null, msj);
    }
    
    public void guardarPlantasFlores(){
        String msj = "";
        for (int i = 0; i < 5; i++) {
            String dato = (String) matriz[i][1];
            if (dato.equalsIgnoreCase("Con flor")) {
                plantasConFlor[i] = (String) matriz[i][0];
            } 
        }
        
        for (int i = 0; i < 5; i++) {
            if (plantasConFlor[i]!= null) {
                msj += plantasConFlor[i]+" | ";
            }  
        }
        JOptionPane.showMessageDialog(null, "PLANTAS CON FLOR \n" + msj);
    }
    
    public void getPorcentajePlantasSombra(){
        int cantidadPlantasSombra = 0;
        for (int i = 0; i < 5; i++) {
            String dato = (String) matriz[i][3];
            if (dato.equalsIgnoreCase("Sombra")) {
                cantidadPlantasSombra++;
            } 
        }
        if (cantidadPlantasSombra == 0) {
           JOptionPane.showMessageDialog(null, "No hay plantas con ambiente sombra " ); 
        } else {
           JOptionPane.showMessageDialog(null, "PORCENTAJE PLANTAS CON AMBIENTE SOMBRA"
                   + "\n" + (cantidadPlantasSombra * 100 / 5) + "% ");
        } 
    }
    
    public void getTresDatosIguales(){
        int cantidadDatosIguales = 0;
        for (int i = 0; i < 5; i++) {
            String ambiente = (String) matriz[i][3];
            String clasificacion = (String) matriz[i][1];
            String tipo = (String) matriz[i][2];
            if (ambiente.equalsIgnoreCase("Sombra") && tipo.equalsIgnoreCase("pteridofitas")
                    && clasificacion.equalsIgnoreCase("Sin flor")) {
                cantidadDatosIguales++;
            } 
        }
        if (cantidadDatosIguales == 0) {
           JOptionPane.showMessageDialog(null, "No hay plantas con los 3 datos iguales " ); 
        } else {
           JOptionPane.showMessageDialog(null, "Hay "+ cantidadDatosIguales + " plantas de tipo pteridofitas, sin flor y con ambiente de sombra ");
        }
        
        
    }
    
    //Verificar que el cliente seleccione algun opción 
    public boolean verificarNombre(String nombre){
        for (int i = 0; i < 5; i++) {
            if (nombre.equalsIgnoreCase(nombres[i])){
                intentos[i] += 1;
                return true;
            }
        }
        
        return false;
    }  
    
    public boolean verificarTodo(String name, String type,String clase,
            String ambiente, String uno, String dos ){
        return "Seleccione".equalsIgnoreCase(name) || 
                "Seleccione".equalsIgnoreCase(clase) ||
                "Seleccione".equalsIgnoreCase(type) ||
                "Seleccione".equalsIgnoreCase(ambiente) ||
                "Seleccione".equalsIgnoreCase(uno) ||
                "Seleccione".equalsIgnoreCase(dos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbClafication = new javax.swing.JComboBox();
        cbType = new javax.swing.JComboBox();
        cbEnviroment = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbName = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        panelSinFlor = new javax.swing.JPanel();
        cbTipoAgua = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbColorEsporas = new javax.swing.JComboBox();
        panelConFlor = new javax.swing.JPanel();
        cbCantidadColores = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbColorPrincipal = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbClafication.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Sin flor", "Con flor" }));
        cbClafication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClaficationActionPerformed(evt);
            }
        });

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "briofitas", "pteridofitas", "gimnospermas", "angiospermas" }));

        cbEnviroment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Sol", "Sombra" }));

        jLabel1.setText("Clasificación");

        jLabel2.setText("Ambiente");

        jLabel3.setText("Tipo");

        jLabel5.setText("Nombre");

        jLabel6.setText("REGISTRAR PLANTAS");

        cbName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Orquidea", "Helecho", "Musgo", "Rosa", "Clavel" }));
        cbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNameActionPerformed(evt);
            }
        });

        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        panelSinFlor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cbTipoAgua.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Salada", "Dulce" }));

        jLabel4.setText("Color esporas");

        jLabel7.setText("Tipo de agua");

        cbColorEsporas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Rojo", "Azul", "Morado", "Verde", "Amarillo" }));

        javax.swing.GroupLayout panelSinFlorLayout = new javax.swing.GroupLayout(panelSinFlor);
        panelSinFlor.setLayout(panelSinFlorLayout);
        panelSinFlorLayout.setHorizontalGroup(
            panelSinFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinFlorLayout.createSequentialGroup()
                .addGroup(panelSinFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSinFlorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(panelSinFlorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbColorEsporas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(panelSinFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelSinFlorLayout.setVerticalGroup(
            panelSinFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSinFlorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSinFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSinFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbColorEsporas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        panelConFlor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cbCantidadColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel8.setText("Color Principal");

        jLabel9.setText("Cantidad de colores");

        cbColorPrincipal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Rojo", "Azul", "Morado", "Verde", "Amarillo", "Rosado", " " }));

        javax.swing.GroupLayout panelConFlorLayout = new javax.swing.GroupLayout(panelConFlor);
        panelConFlor.setLayout(panelConFlorLayout);
        panelConFlorLayout.setHorizontalGroup(
            panelConFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFlorLayout.createSequentialGroup()
                .addGroup(panelConFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConFlorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8))
                    .addGroup(panelConFlorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbColorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(panelConFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCantidadColores, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConFlorLayout.setVerticalGroup(
            panelConFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConFlorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConFlorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCantidadColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbColorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jButton1.setText("Imprimir plantas con flor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Porcentaje plantas en sombra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cantidad de intentos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("3 datos iguales");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEnviroment, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbClafication, 0, 107, Short.MAX_VALUE)
                                    .addComponent(cbName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSinFlor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelConFlor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(cbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbClafication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEnviroment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSinFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(registros != 5){
            String name = cbName.getSelectedItem().toString();
            String type = cbType.getSelectedItem().toString();
            String clase  = cbClafication.getSelectedItem().toString();
            String ambiente  = cbEnviroment.getSelectedItem().toString();
            String uno="", dos="";
            
            if(cbClafication.getSelectedItem().toString().equals("Sin flor")){
                uno = cbColorEsporas.getSelectedItem().toString();
                dos  = cbTipoAgua.getSelectedItem().toString();
            } else if(cbClafication.getSelectedItem().toString().equals("Con flor")){
                uno  = cbColorPrincipal.getSelectedItem().toString();
                dos = cbCantidadColores.getSelectedItem().toString();
            }

            if (verificarTodo(name, type, clase, ambiente, uno, dos)) {
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            } else {
                if (verificarNombre(name)) {
                    JOptionPane.showMessageDialog(null, "El nombre ya se encuentra almacenado");
                } else {
                   
                    nombres[registros] = name;
                    tipos[registros] = type;
                    matriz[registros][0] = name;
                    matriz[registros][1] = clase;
                    matriz[registros][2] = type;
                    matriz[registros][3] = ambiente;

                    registros++;
                    JOptionPane.showMessageDialog(null, "Almacenado con éxito");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Al parecer ya guardaste 5 plantas, no es posible guardar más");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNameActionPerformed
       
    }//GEN-LAST:event_cbNameActionPerformed

    private void cbClaficationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClaficationActionPerformed
         try {
            if(cbClafication.getSelectedItem().toString().equals("Sin flor")){
                panelSinFlor.setVisible(true);
                panelConFlor.setVisible(false);
            } else if(cbClafication.getSelectedItem().toString().equals("Con flor")){
                panelConFlor.setVisible(true);
                panelSinFlor.setVisible(false);
            } else {
                panelConFlor.setVisible(false);
                panelSinFlor.setVisible(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbClaficationActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(registros == 5){
            imprimirIntentos();
        } else {
            JOptionPane.showMessageDialog(null, "Esta opción solo está disponible cuando se ingresan las 5 plantas");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(registros == 5){
            guardarPlantasFlores();
        } else {
            JOptionPane.showMessageDialog(null, "Esta opción solo está disponible cuando se ingresan las 5 plantas");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(registros == 5){
            getPorcentajePlantasSombra();
        } else {
            JOptionPane.showMessageDialog(null, "Esta opción solo está disponible cuando se ingresan las 5 plantas");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(registros == 5){
            getTresDatosIguales();
        } else {
            JOptionPane.showMessageDialog(null, "Esta opción solo está disponible cuando se ingresan las 5 plantas");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbCantidadColores;
    private javax.swing.JComboBox cbClafication;
    private javax.swing.JComboBox cbColorEsporas;
    private javax.swing.JComboBox cbColorPrincipal;
    private javax.swing.JComboBox cbEnviroment;
    private javax.swing.JComboBox cbName;
    private javax.swing.JComboBox cbTipoAgua;
    private javax.swing.JComboBox cbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelConFlor;
    private javax.swing.JPanel panelSinFlor;
    // End of variables declaration//GEN-END:variables
}
